### ISSUE TITLE
the Mersey

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-load#15]
when one runs route network then crossing the Mersey comes out comes out as important straight away (e.g. 2% of route network) but when doing flows from OD pairs then even on 100 it does not register- of course it is a concentration point for flows so maybe this is right but it seems too extreme.

**Comment by Robinlovelace** [comment]
@JDWoodcock there's no action point on this so closing

**Comment by JDWoodcock** [comment]
the action point is check if there is a bug!

**Comment by Robinlovelace** [comment]
Ah OK - will re-open for now.

**Comment by Robinlovelace** [comment]
@JDWoodcock any further info? Still not sure of the action to be taken...

**Comment by JDWoodcock** [comment]
currently no-one is crossing the Mersey so it is consistent

**Comment by Robinlovelace** [comment]
Thanks James.
