### ISSUE TITLE
Anna & Robin to align scenario building + all flows contribute to area-level estimates

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-load#19]
Anna to revisit method for developing scenarios, inc ebikes, and agree with robin - Robin then to implement in R.

All flows with euclidean distance <30km to contribute to area-level estimates of cycling scenarios - this can be pre-calculated.

**Comment by Robinlovelace** [comment]
Good progress using Anna's data. Will leave open as a reminder to eventually build national data with R.

**Comment by Robinlovelace** [comment]
Completed now
