### ISSUE TITLE
avslope missing in aggregate

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-load#2]
@Robinlovelace any idea where avslope comes from?

``` R
> source(file.path("components", "models", "aggregate.R")) # this model creates the variable 'slc'
Error in eval(expr, envir, enclos) : object 'avslope' not found
```

**Comment by Robinlovelace** [comment]
Hi @nikolai-b - this will become obsolete when we use the much more intelligent route-allocated hilliness. Will look at that today, and other reproducibility issues, from my WINDOWS computer hehe.

**Comment by Robinlovelace** [comment]
I think this is sorted now. I've added avslope back in, from rf$av_incline . Now need to update the model to use this new data.
