### ISSUE TITLE
Add travel by train data later

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#25]
@mattturner86 has illustrated that this works and generates interesting and potentially useful results.

**Comment by mattturner86** [comment]
Take a look here: https://github.com/mattturner86/PropensityToCycleHackDay/tree/master/OD%20Train%20Station

A rough and ready R implementation of this.

Download the files, load into R, process them, create the route network (using an altered version of od2line) and create a travel network from CycleStreets data.

No statistics however, the data surrounding the number of people making this journey hasn't been introduced.

You can view the output geoJSON file on a nice map here: https://github.com/mattturner86/PropensityToCycleHackDay/blob/master/OD%20Train%20Station/OA_Sheffield.geojson

**Comment by Robinlovelace** [comment]
Part of phase 3. Will reopen when that's approved.
