### ISSUE TITLE
Remove unnecessary columns from data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#28]

**Comment by audev** [comment]
@Robinlovelace  I take this is a generic rule to follow, or does it refer to specific .Rds /datasets in pct-load?

**Comment by Robinlovelace** [comment]
@audev this issue relates to the data we serve, not the data that we use in the model.

It simply means removing columns as the last stage - hence allocated to me.

**Comment by nikolai-b** [comment]
This has been addressed in https://github.com/npct/pct-load/commit/dc1b5ef8d7d29e1f6f579a83f7e399d966d0b795 and a few other commits

**Comment by Robinlovelace** [comment]
Thanks for closing this
