### ISSUE TITLE
Add HEAT estimates to model flows

### ISSUE THREAD

**Issue by audev** [npct/pct-load#29]
The idea is to implement the HEAT model  in npct (http://www.euro.who.int/__data/assets/pdf_file/0010/256168/ECONOMIC-ASSESSMENT-OF-TRANSPORT-INFRASTRUCTURE-AND-POLICIES.pdf?ua=1).

3 main steps:
1. Create Heat-Calculation subfolder.
2. Calculate HEAT values per flow.
3. Display the outcomes on the flow popups.

**Comment by audev** [comment]
@Robinlovelace  Any reason to comment L96 in load.Rmd ?

`# regions <- readOGR(file.path(pct_bigdata, "regions.geojson"), layer = "OGRGeoJSON`

I've traced it back to this(https://github.com/npct/pct-load/commit/386ff5fd037d8223670f28ffcb9653798e13a768). Previously it was a more cautious if-else.

I was about to test some HEAT nos. and bumped into it.

**Comment by audev** [comment]
Asking not out curiosity: it prevents it from running! :0

**Comment by Robinlovelace** [comment]
@audev that line loads the old 'CUA' regional boundaries: https://github.com/npct/pct-bigdata/blob/master/regions.geojson

Now we use the new regional boundaries which I defined, of which there are 45. This is loaded here: https://github.com/npct/pct-load/commit/477b57ad9afb3292e501cfd6ffd2a3a5f77742df#diff-f728b105860d99bed1d5f0718c4ec40bR88

Update - it's loaded here (correct link): https://github.com/npct/pct-load/blame/master/load.Rmd#L87

**Comment by audev** [comment]
Problem is this: Before it read the json file _only_ when geo_level == "cua", otherwise the json:

```
if(geo_level == "cua"){
  regions <- readOGR(dsn = file.path(pct_bigdata, "cuas-mf.geojson"), layer = "OGRGeoJSON")
  regions$Region <- regions$CTYUA12NM
}

 regions <- readOGR(file.path(pct_bigdata, "regions.geojson"), layer = "OGRGeoJSON")


```

Now it doesn't read it, as by default geo_level ='regions' .   Am I missing sth? Or is it that pct-bigdata repository needs re-pulling?

**Comment by audev** [comment]
I've rerun and it's reading region_shape. No problem , thanks

**Comment by Robinlovelace** [comment]
No there was an issue with this: fixing it now, my bad.

**Comment by Robinlovelace** [comment]
Apologies - these are the correct regions and the new script loads them by default. I was playing around with `geo_level = 'custom'` and accidentally removed that part. Fixed here: https://github.com/npct/pct-load/commit/24c085201997e5c67e39b5dec661e3f828b6ce3f

**Comment by audev** [comment]
No worries, just wanted it for having real figures.

**Comment by Robinlovelace** [comment]
Done by @annagoodman1 but still needs to be done...

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/229
