### ISSUE TITLE
Standardized Naming of Local Authorities

### ISSUE THREAD

**Issue by usr110** [npct/pct-load#3]

**Comment by Robinlovelace** [comment]
Made progress on this - the front page is now up-to-date for all regions and links to lower-case zones: http://geo8.webarch.net/ Will do a test build for Liverpool City Region to check the urls work

**Comment by usr110** [comment]
@Robinlovelace Great work!

**Comment by Robinlovelace** [comment]
Thanks - we need to be super fast ready for the national level roll-out. Can you remove the print-screen if you get a chance? Happy holidays in any case!!

**Comment by usr110** [comment]
Oh yes, you are quite right. Thanks and happy holidays to you too.
Did you mean the "print map" functionality? If yes, sure I can remove it. It'd be nice if you create an issue for it.

**Comment by Robinlovelace** [comment]
Job done :+1:
