### ISSUE TITLE
Explore using datastorr to store data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#39]
I've just been reading another option for storing data that has some advantages: http://richfitz.github.io/datastorr/vignettes/datastorr.html

Any thoughts on this approach @nikolai-b?

**Comment by nikolai-b** [comment]
It looks nice but isn't quite what we need.  I spent some time trying to get it to fit our use case but decided against.

**Comment by Robinlovelace** [comment]
Sounds good but reopening as we've not resolved the issue of distributing large binaries - we should agree a system. Check out how I'm dealing with the multi GB files we use for the local builds: https://github.com/npct/pct-bigdata/releases

Unfortunately the complete national rf/rq files are > the 2GB limit described here: https://help.github.com/articles/distributing-large-binaries/ 

Any suggestions how to deal with that? Thinking atm is to simplify them first and then use releases. Do you agree @nikolai-b ?
