### ISSUE TITLE
rnet is huge, slowing down pct-shiny

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#4]
Just generated rnet for http://geo8.webarch.net/gm and it's seeming pretty slow to load.

Even after simplifying to only 5% of its vertices with `stplanr::mapshpe()` it still seems slow to load - at 50% of the network this is what it looks like:

![selection_043](https://cloud.githubusercontent.com/assets/1825120/11986536/a0102382-a9c8-11e5-9aea-94a48c1f08ab.png)

Given that the `overline()` commands are by far the slowest in `load.Rmd` I'm thinking we should simplify directly after generating `rf` and `rq`, perhaps using `snap` and `precision` from the mapshaper JavaScript library: https://github.com/mbloch/mapshaper/wiki/Command-Reference

I'd appreciate your thoughts @nikolai-b and @usr110 before proceeding with this - what are your thoughts?

**Comment by Robinlovelace** [comment]
Only issue I see - could be seen as _too_ simplified when only 5% of vertices are retained. On the other hand it seems to be faster. Will try for a larger area and see. @nikolai-b and @JDWoodcock could I get your view on this level of simplification: too much?

Before:

![selection_053](https://cloud.githubusercontent.com/assets/1825120/12079923/1ddde4ee-b242-11e5-9a4c-692daf9ebe62.png)

After:

![selection_052](https://cloud.githubusercontent.com/assets/1825120/12079925/28994eaa-b242-11e5-84b3-2ef032cf12ba.png)

**Comment by JDWoodcock** [comment]
hi so the issue here is that it doesn't exactly follow the road network? If so then that is probably okay -as road network is not always exact route anyway. Certainly if large speed up then yes.

**Comment by Robinlovelace** [comment]
@JDWoodcock yes that's the issue - and agreed it's not a big problem.

**Comment by JDWoodcock** [comment]
looking at tunbridge wells, Kent I find it not loading too slowly but sometimes the match to the network is poor, e.g. Landsdowne road- see attached.

I also wonder if we should have some kind of hour glass thing to show people when it is still loading? It is easy to think it is loaded and wrong when it hasn't loaded yet.

**Comment by Robinlovelace** [comment]
Hi @JDWoodcock please be precise about what you would like to see changed. Less aggressive simplification for Kent and everywhere? Would the max value of 50% not solve this? I think not matching the route network could be an advantage: these are only rough 'desire lines'.

**Comment by JDWoodcock** [comment]
@Robinlovelace I suggest we bring a few examples to the meeting to discuss route network- tighter snapping to the route network is desirable but clearly trade-offs are needed.

**Comment by nikolai-b** [comment]
We are simplifying rnet more now

**Comment by JDWoodcock** [comment]
@nikolai-b can I check if simplifying means a less good fit with the route network? If so please can we know when it is done so we can check if it is okay.

**Comment by Robinlovelace** [comment]
It's done for kent - we can increase or decrease the level of simplification @JDWoodcock your understanding of it seems correct

**Comment by JDWoodcock** [comment]
Currently on my computer (i5 8gb) it is running nicely and I think simplification level is okay for Kent. Quickly goes to 50% of route network- probably could see higher % but want to see how it works for a region with more flows first- let me know when a big region is ready to test.

**Comment by Robinlovelace** [comment]
:+1:
