### ISSUE TITLE
Fix quiet routes in Cambridge

### ISSUE THREAD

**Issue by usr110** [npct/pct-load#46]

**Comment by usr110** [comment]
The data is missing in lines data - lots of variables are missing. I believe new data is needed to be created for Cambridgeshire.

> > colnames(l@data)
> >  [1] "plan"        "start"       "finish"      "length"      "time"        "waypoint"  
> >  [7] "change_elev" "av_incline"  "co2_saving"  "calories"    "busyness"    "id" 

It should have these columns - taken from kent:

> colnames(l@data)
>  [1] "id"                       "Area.of.residence"        "Area.of.workplace"  
>  [4] "All"                      "light_rail"               "Bus"  
>  [7] "Taxi"                     "Motorbike"                "Car_driver"  
> [10] "Car_passenger"            "Bicycle"                  "Foot"  
> [13] "Other"                    "govtarget_slc"            "govtarget_sic"  
> [16] "govtarget_slw"            "govtarget_siw"            "govtarget_sld"  
> [19] "govtarget_sid"            "gendereq_slc"             "gendereq_sic"  
> [22] "gendereq_slw"             "gendereq_siw"             "gendereq_sld"  
> [25] "gendereq_sid"             "dutch_slc"                "dutch_sic"  
> [28] "dutch_slw"                "dutch_siw"                "dutch_sld"  
> [31] "dutch_sid"                "ebike_slc"                "ebike_sic"  
> [34] "ebike_slw"                "ebike_siw"                "ebike_sld"  
> [37] "ebike_sid"                "base_sldeath_webtag"      "base_slvalue_webtag"  
> [40] "govtarget_sldeath_webtag" "govtarget_slvalue_webtag" "govtarget_sideath_webtag"
> [43] "govtarget_sivalue_webtag" "gendereq_sldeath_webtag"  "gendereq_slvalue_webtag" 
> [46] "gendereq_sideath_webtag"  "gendereq_sivalue_webtag"  "dutch_sldeath_webtag"  
> [49] "dutch_slvalue_webtag"     "dutch_sideath_webtag"     "dutch_sivalue_webtag"  
> [52] "ebike_sldeath_webtag"     "ebike_slvalue_webtag"     "ebike_sideath_webtag"  
> [55] "ebike_sivalue_webtag"     "base_sldeath_heat"        "base_slvalue_heat"  
> [58] "govtarget_sldeath_heat"   "govtarget_slvalue_heat"   "govtarget_sideath_heat"  
> [61] "govtarget_sivalue_heat"   "gendereq_sldeath_heat"    "gendereq_slvalue_heat"  
> [64] "gendereq_sideath_heat"    "gendereq_sivalue_heat"    "dutch_sldeath_heat"  
> [67] "dutch_slvalue_heat"       "dutch_sideath_heat"       "dutch_sivalue_heat"  
> [70] "ebike_sldeath_heat"       "ebike_slvalue_heat"       "ebike_sideath_heat"  
> [73] "ebike_sivalue_heat"       "base_slco2"               "govtarget_slco2"  
> [76] "govtarget_sico2"          "gendereq_slco2"           "gendereq_sico2"  
> [79] "dutch_slco2"              "dutch_sico2"              "ebike_slco2"  
> [82] "ebike_sico2"              "Rail"                     "dist"  
> [85] "dist_fast"                "dist_quiet"               "time_fast"  
> [88] "time_quiet"               "cirquity"                 "distq_f"  
> [91] "avslope"                  "co2_saving"               "busyness"  
> [94] "avslope_q"                "clc"

**Comment by usr110** [comment]
Generated data for Cambridgeshire (by running load.Rmd) which fixed the issue. 

![cambridge-dataset](https://cloud.githubusercontent.com/assets/10958628/14648378/de10b0e6-0659-11e6-9216-deb1cd2aab24.png)

**Comment by Robinlovelace** [comment]
Thanks for such a clear issue report Ali. Must be that it didn't run in the national build for some reason. Will look to fix this.

**Comment by Robinlovelace** [comment]
@usr110 please can you test that this has worked and re-open if it has not. Pushed onto the main server. Robin

**Comment by usr110** [comment]
@Robinlovelace Working fine. Great work!

**Comment by Robinlovelace** [comment]
Thanks for the report and the feedback @usr110

**Comment by usr110** [comment]
It seems both

> length
> rqincr 

still have some issues, as it's showing very weird values. 

![cambridge-distance](https://cloud.githubusercontent.com/assets/10958628/14857236/608e7a50-0c93-11e6-8b36-947671a012f0.png)

**Comment by Robinlovelace** [comment]
Thanks @usr110, please could you see if these exist in any other regions? I'll look into it and fix.

**Comment by usr110** [comment]
I have just noticed this issue in cornwall and isles of scilly as well. See  below:

![cornwall](https://cloud.githubusercontent.com/assets/10958628/14883751/e73b8e90-0d37-11e6-875e-afc88a59287d.png)

to further investigate the matter, I have looked into both rf.Rds and rq.Rds and found no abnormal behavirours:

> summary(rq@data$length)
>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
>   0.696   6.904  12.710  13.040  18.580  34.520 
> 
> summary(rf@data$length)
>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
>   0.696   6.475  11.560  11.890  16.800  28.130       2 

so the issue must be when the region-specific data is be being generated.

**Comment by Robinlovelace** [comment]
Thanks for investigating. Those summary datasets are for the regions in which incorrect data is being shown, right?

**Comment by usr110** [comment]
yes, robin. Here's summary of Cambridgeshire's rq data:

> summary(rq@data$length)
>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
>     1.062    20.330  9508.000  9828.000 16960.000 29300.000

**Comment by Robinlovelace** [comment]
OK great - that will go into the automated data checking script also. Will fix asap.

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/237
