### ISSUE TITLE
Make all zones isolated

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#51]
This was agreed by others - sorry @nikolai-b

**Comment by nikolai-b** [comment]
Please don't :weary:
It makes comparing regions significantly harder.

**Comment by usr110** [comment]
Just to be clear: I never agreed.

**Comment by Robinlovelace** [comment]
To be clear: Rachel, James and I agreed. The problem is that it breaks the principle of least astonishment (POLA): https://en.wikipedia.org/wiki/Principle_of_least_astonishment

When using the tool it is natural to zoom right out to take a look around. If you're not expecting it it can be confusing when it jumps. Rachel and I have had this reported at user testing sessions.

A technical (not user experience) problem is that because we have overlapping regions with London-east etc when it lands on one of these (which must be isolated) it gets stuck. If you could add a line or two of code preventing it ever jumping into an isolated region @nikolai-b I would be one step closer from changing my mind on this but still quite strongly in favour of this based purely on the POLA argument outlined above. 

Comments @RachelAldred and @JDWoodcock pls.

**Comment by JDWoodcock** [comment]
I agree with @Robinlovelace but i haven't heard @nikolai-b or @audev position so let's put this on agenda for next week and finalise then. If people want to send their reasoning by email in advance that would be helpful.

**Comment by nikolai-b** [comment]
When I move a map I expect the data to move, that would be my POLA.  Agree about some zones being isolated and therefore getting stuck.  It would be easy to add code to prevent jumps to isolated regions.  When I have shown the tool to people they scroll around and are confused as to why the map doesn't update.

**Comment by JDWoodcock** [comment]
I am tempted to say we leave as it (apart from removing isolated regions) until we get user feedback

**Comment by nikolai-b** [comment]
Ok, happy to close this til then?

**Comment by JDWoodcock** [comment]
yes
