### ISSUE TITLE
Update model output tab

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#55]
This involves running the updated version of this for all regions (probably with data checking in there too):

https://github.com/npct/pct-load/blob/master/model_output.Rmd

**Comment by Robinlovelace** [comment]
You up for this @nikolai-b ?

**Comment by Robinlovelace** [comment]
Bump

**Comment by nikolai-b** [comment]
Happy to do for a selection of regions but makes sense to check them out before trying all.  I'm building:

``` r
c("cambridgeshire", "avon", "kent", "london-central")
```

**Comment by RachelAldred** [comment]
Thanks! PS I'm not sure London sub-regions are worth doing at this stage - assuming London central is a sub-region. You lose so many commutes that the gain in resolution is outweighed IMO.

**Comment by RachelAldred** [comment]
Thanks @nikolai-b :) As discuss on Friday, still to do at this stage: implementing the three missing numbers below (total number of commuters in region, % of flows in region that are within-zone, and % of area-based commutes that are included in flow-based routing).

Data for kent were generated at Fri May 6 14:18:08 2016 by the National Propensity to Cycle Tool (PCT) Version 1, developed by the PCT academic team and released with an GPL Affero Licence. This version examines cycling potential for main-mode commute trips using Census 2011 travel to work data and Middle-Level Super Output areas (MSOASs) as zones. There were <!– PLS ADD NUMBER COMMUTERS–> commuters in the study area, all of which were included in area-based analysis. Where cycle flows are routed, flows within zones ( <!–PLS add % of all flows that are within-zone–> of flows in kent ) are excluded as are commuters with no fixed workplace. Of the 3536 between-zone regular commute flows, selection criteria were used. For OD pairs with maximum Euclidean distance of 20, flows with a minimum flow of 30 were selected. For OD pairs with maximum Euclidean distance of 7, flows with a minimum flow of 30 were selected. Adding those (overlapping) selection criteria resulted in 91% of all inter-zone commutes in the study area being selected, accounting for ( <!–PLS add % of all commutes included in area-based data that this represents–> of total commutes in kent). A modified version of the 2014 HEAT tool was used.

**Comment by RachelAldred** [comment]
Sorry, was trying to assign all of us to it! Doesn't seem possible.

**Comment by Robinlovelace** [comment]
Haha the trails and tribulations of 'agile' working eh ;)

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/235
