### ISSUE TITLE
Produce a true list of dependancies

### ISSUE THREAD

**Issue by mem48** [npct/pct-load#64]
While trying to rebuild the routes, I'm getting lots of fails because packages are not installed.

In theory set-up.R should list all the packages, but clearly it does not so I'm going to list them here as they fail, so that we can produce a better list.

**Comment by mem48** [comment]
BBmisc - while running buildmaster.R

Loading required package: BBmisc
Quitting from lines 45-60 (model_output.Rmd) 
Error in capitalize_region(region) : 
  could not find function "capitalizeStrings"
In addition: Warning messages:
1: In left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y) :
  joining character vector and factor, coercing into character vector
2: In dir.create(region_dir) :
  '..\pct-shiny\regions_www\london' already exists
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'BBmisc'

**Comment by Robinlovelace** [comment]
Solved by 00.R which lists all depends at outset.
