### ISSUE TITLE
Change regional boundaries

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-load#7]
There should be a Combined Authority for the North East. This covers Northumberland, County Durham and Tyne and Wear.

**Comment by JDWoodcock** [comment]
And please move Coventry from West Midlands to Warwickshire

**Comment by Robinlovelace** [comment]
Sounds logical from a geographical perspective although from a poli-cy/tics perspective this is less clear. When I presented the west-midlands map to the NCWIP meeting people said it matched their thinking. I suggest we consult with the key players involved before committing to this. Thanks for raising this in any case.

**Comment by JDWoodcock** [comment]
Were these people from Coventry or Birmingham?

**Comment by Robinlovelace** [comment]
Bham.

**Comment by JDWoodcock** [comment]
I think the Cov planners are the ones to ask. Few people will be going by bike from Cov to Brum. But plenty of people will go from south of Cov into Cov & vice versa. The current set up is even leaving Warwick Uni out of Cov- and we know that currently has the biggest cycle flows.

**Comment by Robinlovelace** [comment]
Can you ask the relevant Coventry people then, seeing as you're from there? Thanks.

**Comment by JDWoodcock** [comment]
as it is currently it doesn't work as we know major flows in Cov by bike are to Warwick Uni. So they will say change it. Other option would be to add Uni and perhaps other areas to north and south to W Midlands. But then what would be left in Warwickshire?

**Comment by Robinlovelace** [comment]
Perhaps - worth asking them which region they'd like coventry in. The Uni issue can also be solved with a buffer.

**Comment by JDWoodcock** [comment]
okay we have the confimation now- Cov wants to be in Warwickshire

**Comment by Robinlovelace** [comment]
@JDWoodcock great - but the point of issues is that they are only closed when the work has been done and I've not done it yet! Look forward to closing this with a commit in the next week or so :-)

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/228
