### ISSUE TITLE
need if statements in region stats

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-load#83]
@Robinlovelace / @usr110  / @nikolai-b , can anyone fix this if statement in rmd for me? almost but not quite working....

in https://github.com/npct/pct-scripts/blob/master/commute/msoa/region_stats.Rmd, line 67. First if works fine, second doesn't as I can;t work out how to embed an R number. code not working is:

`r if(region_build_param$mingodutch_rnet!=0){paste0("In the online version of the clickable route network we only present route segments that contain at least", `r region_build_param$mingodutch_rnet cyclists`, " in the Go Dutch scenario. The downloads include all route segments."}`

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , do you know how to fix this? thanks...

**Comment by Robinlovelace** [comment]
Hey Anna, please see https://github.com/npct/pct-scripts/commit/c67567f60a66a89e6771a12c787ba92b943cf946

That should do it - with an `if() else {}` statement - more clear with the code separate from the text - not tested yet though. Cheers for the nudge and thanks for the amazing work!

**Comment by AnnaGoodman1** [comment]
yes works perfectly, thanks @Robinlovelace !
